"""
Django settings for soccertime project.

Generated by 'django-admin startproject' using Django 5.1.3.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

import os
from pathlib import Path

from django.core.exceptions import ImproperlyConfigured
from django.utils.csp import CSP

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


def env_flag(name: str) -> bool:
    """Read a boolean setting from the environment, defaulting to off."""
    return os.environ.get(name, "").lower() == "true"


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env_flag("DJANGO_DEBUG")

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.environ.get("DJANGO_SECRET_KEY")

if not SECRET_KEY:
    if DEBUG:
        SECRET_KEY = "dev-only-insecure-key-not-for-production"
    else:
        raise ImproperlyConfigured("DJANGO_SECRET_KEY environment variable is required in production")

ALLOWED_HOSTS = os.environ.get("DJANGO_ALLOWED_HOSTS", "").split(",") if os.environ.get("DJANGO_ALLOWED_HOSTS") else []


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "adminsortable2",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "django.contrib.humanize",
    "rest_framework",
    "drf_spectacular",
    # Swagger UI's own assets, collected from here rather than fetched from a CDN the
    # Content-Security-Policy would refuse.
    "drf_spectacular_sidecar",
    "soccertime.apps.SoccertimeConfig",
]

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    # Nothing compressed anything before this — not Django, not nginx, not Traefik — so
    # `/competitions/` really did send its 331 KB. The markup is repetitive and gzip returns
    # better than eleven to one on it, which is what makes the favourites page affordable now
    # that it carries the whole window for the browser to filter: 437.1 KB became 38.1 KB,
    # measured against a copy of the production database.
    #
    # Above `ConditionalGetMiddleware`, per Django's documented ordering. Responses travel
    # outwards through this list in reverse, so the ETag is computed on the page and this
    # then marks it as standing for the compressed body. A test asserts that a browser
    # asking for gzip still gets its 304, because `cached_page` is built on that.
    #
    # BREACH does not apply: these pages carry no secret to guess at. Anonymous visitors get
    # no session, the public forms are GET and carry no CSRF token, and the admin — the one
    # place with either — is switched off in production and never compressed here anyway.
    "django.middleware.gzip.GZipMiddleware",
    # Turns the revalidation that `cached_page` asks browsers for into a 304 with no
    # body, by attaching an ETag to the response. Without it every revalidation would
    # send the whole page again, which would be worse than the hour of staleness it
    # replaces. Placed high, per Django's documented ordering, so it sees the final
    # response whatever produced it.
    "django.middleware.http.ConditionalGetMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "django.middleware.csp.ContentSecurityPolicyMiddleware",
]

_caching_enabled = not DEBUG and os.environ.get("DJANGO_CACHE", "true").lower() != "false"

ROOT_URLCONF = "soccertime.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [BASE_DIR / "templates"],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "soccertime.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

# `init_command` is split on `;` and applied statement by statement to every new connection.
# Both PRAGMAs are idempotent, and the journal mode is recorded in the file itself, so this
# is what makes a fresh database — a `resetdb`, a restored snapshot — come up configured
# rather than inheriting whatever it was written with.
#
# **WAL, because a writer must stop blocking every reader.** Under the default rollback
# journal a write takes an exclusive lock over the whole file: readers wait, and at
# `timeout` they are answered `database is locked`, which reaches a visitor as a 500. That
# was survivable while the pages came from an hour-long cache and the only writer was the
# hourly scrape — the two rarely met. The API is not cached, so every request goes to the
# database and the meeting became likely. `test_sqlite_journal.py` holds a write
# transaction open and reads through it; that test fails with the production error message
# without this.
#
# **NORMAL, because WAL is what makes it safe.** With a write-ahead log this survives
# anything the application can do to itself — a crash, an OOM kill, a container stopped
# mid-write. Only the machine losing power can cost the last transactions, and this data is
# rebuilt from its source every hour.
#
# **IMMEDIATE, because a deferred transaction that discovers it needs to write is the one
# that deadlocks.** Taking the write lock at `BEGIN` turns that into an ordinary wait.
#
# Every path that copies or replaces this file has to know that the newest commits live in
# `db.sqlite3-wal` until a checkpoint folds them in. They do — `soccertime/backups.py` reads
# through a connection and `test_database_transport.py` keeps the Makefile honest.
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.sqlite3",
        "NAME": os.environ.get("DJANGO_DATABASE_DEFAULT_NAME", BASE_DIR / "db/db.sqlite3"),
        "OPTIONS": {
            "init_command": "PRAGMA journal_mode=WAL; PRAGMA synchronous=NORMAL;",
            "transaction_mode": "IMMEDIATE",
            "timeout": 20,
        },
    }
}


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "es-es"

# The site is a Spanish TV schedule and its source publishes peninsular time, so every
# visitor sees that clock wherever they are. Storage stays UTC — `USE_TZ` is on — and this is
# only how it is read back. Changing it alone used to do nothing at all: the templates called
# `.time`, which discards the zone before formatting.
TIME_ZONE = "Europe/Madrid"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = os.environ.get("DJANGO_STATIC_URL") or "static/"
STATIC_ROOT = os.environ.get("DJANGO_STATIC_ROOT") or None

# Outside development, every static file is served under a name containing a hash of its
# contents, so changing one changes its URL.
#
# Without this a deploy can only be seen by visitors whose browser happens to ask again:
# nginx sends no `Cache-Control` for these files, only an ETag and a Last-Modified, so
# browsers fall back to heuristic caching of a URL that never changes. Moving the styles
# out of the templates and into `theme.css` for the CSP was the first change where that
# mattered — the pages arrived without their inline styles while the browser kept serving
# the previous `theme.css` from cache, and the site looked broken until a forced reload.
#
# Development keeps the plain backend: `collectstatic` has not run there, and reading
# names from a manifest that does not exist raises on the first page.
STORAGES = {
    "default": {"BACKEND": "django.core.files.storage.FileSystemStorage"},
    "staticfiles": {
        "BACKEND": (
            "django.contrib.staticfiles.storage.StaticFilesStorage"
            if DEBUG
            else "django.contrib.staticfiles.storage.ManifestStaticFilesStorage"
        )
    },
}

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

USE_X_FORWARDED_HOST = env_flag("DJANGO_USE_X_FORWARDED_HOST")
FORCE_SCRIPT_NAME = os.environ.get("DJANGO_FORCE_SCRIPT_NAME") or None
SESSION_COOKIE_PATH = os.environ.get("DJANGO_SESSION_COOKIE_PATH") or None

MEDIA_URL = os.environ.get("DJANGO_MEDIA_URL") or "media/"
MEDIA_ROOT = os.environ.get("DJANGO_MEDIA_ROOT") or BASE_DIR / "media"

if _caching_enabled:
    CACHES = {
        "default": {
            "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
            "LOCATION": os.environ.get("DJANGO_CACHE_LOCATION") or "/var/tmp/soccertime_cache",
            "TIMEOUT": 3600,
        },
        # The API throttle's counters, kept apart from the pages: every cache backend here
        # culls itself once it holds `MAX_ENTRIES`, so counting requests in the default
        # store would evict the rendered pages that store exists to keep.
        #
        # In memory rather than on disk. The container runs a single uvicorn worker, so one
        # process sees every request and the count is exact; a restart forgets the counters,
        # which costs one window of allowance and no correctness. The file-based
        # alternative pickles and writes to disk on **every** API request, and would have
        # needed its own tmpfs the day `read_only` is switched on.
        #
        # `MAX_ENTRIES` is the number this whole alias exists for and it is not the default:
        # 300 is, for this backend as much as for the file-based one, so a few hundred
        # distinct callers in one window would start evicting each other's counters and the
        # limit would quietly stop applying to whoever was dropped.
        "throttling": {
            "BACKEND": "django.core.cache.backends.locmem.LocMemCache",
            "LOCATION": "soccertime-throttling",
            "TIMEOUT": 3600,
            "OPTIONS": {"MAX_ENTRIES": 20000},
        },
    }
else:
    # Explicitly nothing, rather than Django's default per-process LocMemCache: with
    # that, the `cache.clear()` the management commands run would appear to succeed
    # while only ever clearing the calling process's own memory.
    CACHES = {"default": {"BACKEND": "django.core.cache.backends.dummy.DummyCache"}}

CACHE_PAGE_TIMEOUT = 3600 if _caching_enabled else 0

FORMAT_MODULE_PATH = ["soccertime.formats"]
# --- The REST API ---
#
# Reading only, and to anybody: the site is public and carries no login, so an endpoint
# that serves what the pages already show needs nothing to identify its caller. What it
# does need is a limit, since a listing joins six tables in SQLite and nothing else stands
# between a script and the container that also serves the database.
#
# JSON is the only representation. DRF's browsable API renders forms and a stylesheet of
# its own, which would be the one page here loading inline styles the CSP refuses — and it
# would present write forms for methods no viewset accepts. The human-readable entry point
# is `/api/v1/docs/`.
REST_FRAMEWORK = {
    "DEFAULT_RENDERER_CLASSES": ["rest_framework.renderers.JSONRenderer"],
    "DEFAULT_PARSER_CLASSES": ["rest_framework.parsers.JSONParser"],
    "DEFAULT_PERMISSION_CLASSES": ["rest_framework.permissions.AllowAny"],
    # Nothing authenticates: there is no login here to carry. Leaving DRF's defaults in
    # place would have every request open a session and answer a bad `Authorization`
    # header with a browser password prompt, for an API that grants the same to everybody.
    "DEFAULT_AUTHENTICATION_CLASSES": [],
    "DEFAULT_FILTER_BACKENDS": ["soccertime.api.filtering.QueryFilterBackend"],
    "DEFAULT_PAGINATION_CLASS": "soccertime.api.pagination.Pages",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_THROTTLE_CLASSES": ["soccertime.api.throttling.ApiRateThrottle"],
    # Sized against what a request actually costs on the one CPU the production container
    # is allowed: the events listing is ~140-230 ms of it, so thirty a minute is about a
    # tenth of the machine per caller. It used to be 120, which on the same measurements
    # asked for more CPU than exists — and a saturated container fails its health check,
    # loses its route at the proxy and takes every page down with it.
    "DEFAULT_THROTTLE_RATES": {"api": os.environ.get("DJANGO_API_THROTTLE_RATE") or "30/min"},
    # Who "one caller" is. Without this DRF reads the whole `X-Forwarded-For` header as the
    # identity, so anybody who can put a value in it mints a fresh allowance per request and
    # the limit stops existing. One proxy — Traefik — stands in front, and it appends the
    # peer's address to whatever arrived, so the **last** entry is the real client and a
    # forged prefix changes nothing. Pinned here rather than trusted to the proxy's default
    # of discarding untrusted headers: this project has already been taken down twice by
    # assuming what the layer in front does.
    "NUM_PROXIES": 1,
    "UNAUTHENTICATED_USER": None,
}

SPECTACULAR_SETTINGS = {
    "TITLE": "Soccertime API",
    "DESCRIPTION": (
        "Read-only access to everything the site shows: the events schedule, the "
        "competitions and teams behind it, and the channels and links each event is "
        "carried on. Times are expressed in Europe/Madrid, which is the clock the site "
        "is read in."
    ),
    "VERSION": "1.0.0",
    "SERVE_INCLUDE_SCHEMA": False,
    # Groups the operations by resource rather than by viewset name.
    "SCHEMA_PATH_PREFIX": "/api/v1",
    # Production is served under a script name the URL patterns know nothing about, so
    # without this every path in the document would be one the deployment does not answer
    # — and the mistake is invisible in development, where the prefix is empty.
    "SCHEMA_PATH_PREFIX_INSERT": FORCE_SCRIPT_NAME or "",
    "SORT_OPERATIONS": False,
    "COMPONENT_SPLIT_REQUEST": False,
}


CSRF_TRUSTED_ORIGINS = (
    os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS", "").split(",")
    if os.environ.get("DJANGO_CSRF_TRUSTED_ORIGINS")
    else []
)

# Transport security. TLS is terminated by the reverse proxy, so Django only needs to
# trust the scheme it forwards; enable these wherever the site is actually served over
# HTTPS and leave them off for local development on plain HTTP.
if env_flag("DJANGO_BEHIND_TLS_PROXY"):
    SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")

SESSION_COOKIE_SECURE = env_flag("DJANGO_SECURE_COOKIES")
CSRF_COOKIE_SECURE = SESSION_COOKIE_SECURE

SECURE_SSL_REDIRECT = env_flag("DJANGO_SECURE_SSL_REDIRECT")
# The container health check reaches the app directly over plain HTTP, bypassing the
# proxy that would mark the request secure. Redirecting it returns a 301, the check
# fails, the container is declared unhealthy and the proxy withdraws the route, taking
# the whole site down. Matching is unanchored so it also works under FORCE_SCRIPT_NAME.
SECURE_REDIRECT_EXEMPT = [r"healthz/$"]
SECURE_HSTS_SECONDS = int(os.environ.get("DJANGO_SECURE_HSTS_SECONDS") or 0)
SECURE_HSTS_INCLUDE_SUBDOMAINS = env_flag("DJANGO_SECURE_HSTS_INCLUDE_SUBDOMAINS")
SECURE_HSTS_PRELOAD = env_flag("DJANGO_SECURE_HSTS_PRELOAD")

# The layer that contains an injection rather than preventing it, which is why it is worth
# having even after the stored-XSS finding was fixed at the source.
#
# There is no nonce here, and that is deliberate rather than an omission. Every public view
# is wrapped in `@cache_page` for an hour, and `cache_page` stores the response inside the
# view decorator — before this middleware adds the header. On a cache hit the header would
# therefore carry a freshly minted nonce while the cached HTML still carried the old one,
# and every inline script would be blocked for everyone except the visitor who happened to
# populate the cache. So the inline went away instead: the scripts and styles live in
# static files, and nothing on a page needs permission to run.
#
# Adding a nonce later would not be a small change — it would be an invitation to write an
# inline script that works locally and breaks in production an hour after each deploy.
SECURE_CSP = {
    "default-src": [CSP.SELF],
    "script-src": [CSP.SELF],
    "style-src": [CSP.SELF],
    # The favicon is an inline SVG data URI in `base.html`. Media and static are served
    # from this origin by nginx, so `self` already covers every real image.
    "img-src": [CSP.SELF, "data:"],
    "font-src": [CSP.SELF],
    "connect-src": [CSP.SELF],
    # Alongside `X-Frame-Options: DENY`, which older browsers still need.
    "frame-ancestors": [CSP.NONE],
    "base-uri": [CSP.NONE],
    "form-action": [CSP.SELF],
    "object-src": [CSP.NONE],
}

SILENCED_SYSTEM_CHECKS = [
    # HSTS deliberately covers this host only: the domain may serve unrelated
    # subdomains, and neither includeSubDomains nor preload can be taken back quickly.
    # These two are policy decisions rather than defects, so they stay silenced.
    "security.W005",
    "security.W021",
]
