server {
    listen                      80;
    server_name                 _;

    location /soccertime/static {
        alias /tmp/soccertime-static;
    }

    location /soccertime/media {
        alias /tmp/soccertime-media;
    }
}
