# Generated by Django 5.1.3 on 2024-11-22 23:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Competition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('details', models.TextField(null=True)),
                ('date', models.DateTimeField()),
                ('channels', models.ManyToManyField(to='soccertime.channel')),
                ('competition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='soccertime.competition')),
            ],
            options={
                'ordering': ['date__date', 'competition__sport', 'competition', 'date'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('order', models.PositiveIntegerField(db_index=True, default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(unique=True)),
                ('crest', models.ImageField(null=True, upload_to='crests/%Y/%m/%d/')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='competition',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='competitions', to='soccertime.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='competition',
            unique_together={('name', 'sport')},
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('competition', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='soccertime.competition')),
                ('team', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='favorite', to='soccertime.team')),
            ],
            options={
                'unique_together': {('competition', 'team')},
            },
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soccertime.event')),
                ('local', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_matches', to='soccertime.team')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='away_matches', to='soccertime.team')),
            ],
            options={
                'verbose_name_plural': 'matches',
                'unique_together': {('local', 'visitor', 'event_ptr')},
            },
            bases=('soccertime.event',),
        ),
        migrations.CreateModel(
            name='Race',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soccertime.event')),
                ('name', models.TextField()),
            ],
            options={
                'unique_together': {('name', 'event_ptr')},
            },
            bases=('soccertime.event',),
        ),
        migrations.CreateModel(
            name='ChannelLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=255, null=True)),
                ('subcategory', models.CharField(max_length=255, null=True)),
                ('quality', models.CharField(choices=[('ANY', 'ANY'), ('FHD', 'FHD'), ('HD', 'HD'), ('SD', 'SD')], default='ANY', max_length=255)),
                ('link', models.URLField(max_length=255, null=True, unique=True)),
                ('channel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='channel_links', to='soccertime.channel')),
            ],
            options={
                'verbose_name_plural': 'channels links',
            },
        ),
    ]
