# Generated by Django 5.1.3 on 2024-11-24 22:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0003_channellink_source"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channellink",
            name="link",
            field=models.URLField(max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name="channellink",
            unique_together={("link", "source")},
        ),
    ]
