# Generated by Django 5.1.3 on 2024-11-29 21:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0005_alter_favorite_options_favorite_order_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channellink",
            name="quality",
            field=models.CharField(
                choices=[("ANY", "ANY"), ("UHD", "UHD"), ("FHD", "FHD"), ("HD", "HD"), ("SD", "SD")],
                default="ANY",
                max_length=255,
            ),
        ),
    ]
