# Generated by Django 5.1.3 on 2024-12-07 16:33

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0006_alter_channellink_quality"),
    ]

    operations = [
        migrations.AddField(
            model_name="channel",
            name="logo",
            field=models.ImageField(null=True, upload_to="channel_logos/%Y/%m/%d/"),
        ),
        migrations.AlterField(
            model_name="channellink",
            name="category",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="channellink",
            name="subcategory",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
