# Generated by Django 5.1.3 on 2024-12-08 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('soccertime', '0007_channel_logo_alter_channellink_category_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='channel',
            name='logo',
        ),
    ]
