# Generated by Django 5.1.3 on 2024-12-19 21:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccertime', '0008_remove_channel_logo'),
    ]

    operations = [
        migrations.CreateModel(
            name='SimpleEvent',
            fields=[
                ('event_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='soccertime.event')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'unique_together': {('name', 'event_ptr')},
            },
            bases=('soccertime.event',),
        ),
    ]
