# Generated by Django 5.1.3 on 2025-03-01 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccertime', '0009_simpleevent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='event',
            options={'ordering': ['date__date', 'date', 'competition__sport', 'competition']},
        ),
        migrations.AddField(
            model_name='channellink',
            name='date_added',
            field=models.DateTimeField(default='1970-01-01 00:00:00'),
            preserve_default=False,
        ),
    ]
