# Generated by Django 5.1.3 on 2025-03-01 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0010_alter_event_options_channellink_date_added"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channellink",
            name="date_added",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
