# Generated by Django 5.2 on 2025-04-21 12:12

from django.db import migrations, models

import soccertime.models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0011_alter_channellink_date_added"),
    ]

    operations = [
        migrations.CreateModel(
            name="Flag",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("display_name", models.CharField(max_length=255)),
                ("image", models.ImageField(null=True, upload_to=soccertime.models.gen_upload_to)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
        migrations.AlterField(
            model_name="team",
            name="crest",
            field=models.ImageField(null=True, upload_to=soccertime.models.gen_upload_to),
        ),
    ]
