# Generated by Django 5.2 on 2025-04-21 12:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccertime', '0012_flag_alter_team_crest'),
    ]

    operations = [
        migrations.AddField(
            model_name='competition',
            name='flag',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='competitions', to='soccertime.flag'),
        ),
    ]
