# Generated by Django 5.2.3 on 2025-06-15 19:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0013_competition_flag"),
    ]

    operations = [
        migrations.AddField(
            model_name="channellink",
            name="enabled",
            field=models.BooleanField(default=True),
        ),
    ]
