# Generated by Django 5.2.5 on 2025-08-30 19:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0016_migrate_channel_links"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="channellink",
            name="channel",
        ),
    ]
