# Generated by Django 5.2.5 on 2025-09-29 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0020_alter_channellink_link"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="channellink",
            options={"ordering": ["-verified", "-id"], "verbose_name_plural": "channels links"},
        ),
        migrations.AddField(
            model_name="channellink",
            name="date_updated",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
