# Generated by Django 5.2.8 on 2025-11-29 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccertime', '0021_alter_channellink_options_channellink_date_updated'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='channellink',
            options={'ordering': ['-date_updated__date', 'date_updated__time', '-verified', '-id'], 'verbose_name_plural': 'channels links'},
        ),
        migrations.AlterField(
            model_name='channellink',
            name='link',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
