# Generated by Django 5.2.8 on 2025-11-29 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('soccertime', '0022_alter_channellink_options_alter_channellink_link'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='last_updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
