# Generated by Django 6.0.1 on 2026-01-23 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0027_alter_event_type_non_nullable"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="favorite",
            constraint=models.CheckConstraint(
                condition=models.Q(("competition__isnull", False), ("team__isnull", False), _connector="OR"),
                name="favorite_requires_competition_or_team",
            ),
        ),
    ]
