# Generated by Django 6.0.1 on 2026-08-02 10:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0029_channellinksource_alter_channellink_unique_together_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="team",
            name="futbolenlatv_slug",
            field=models.SlugField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
