# Generated by Django 6.0.1 on 2026-08-04 17:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0030_team_futbolenlatv_slug"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="match",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="race",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="simpleevent",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="event",
            name="duration",
            field=models.DurationField(
                blank=True, help_text="Custom duration of the event (defaults to 2 hours if not set).", null=True
            ),
        ),
        migrations.AlterField(
            model_name="channellink",
            name="link",
            field=models.URLField(
                blank=True,
                max_length=1000,
                null=True,
                validators=[
                    django.core.validators.URLValidator(
                        schemes=["http", "https", "ftp", "ftps", "acestream", "sop", "intent", "rtmp", "m3u8"]
                    )
                ],
            ),
        ),
    ]
