# Generated by Django 6.0.1 on 2026-08-04 17:40

from django.db import migrations, models

import soccertime.models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0031_alter_match_unique_together_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="channellink",
            name="link",
            field=models.CharField(
                blank=True, max_length=1000, null=True, validators=[soccertime.models.validate_channel_link]
            ),
        ),
    ]
