# Generated by Django 6.0.1 on 2026-08-10 16:57

from django.db import migrations, models

import soccertime.models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0033_dedupe_channellink_link_and_make_it_unique"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="event",
            options={"ordering": ["date"]},
        ),
        migrations.AddField(
            model_name="flag",
            name="image_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="flag",
            name="image_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="crest_height",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="team",
            name="crest_width",
            field=models.PositiveIntegerField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name="flag",
            name="image",
            field=models.ImageField(
                height_field="image_height",
                null=True,
                upload_to=soccertime.models.gen_upload_to,
                width_field="image_width",
            ),
        ),
        migrations.AlterField(
            model_name="team",
            name="crest",
            field=models.ImageField(
                height_field="crest_height",
                null=True,
                upload_to=soccertime.models.gen_upload_to,
                width_field="crest_width",
            ),
        ),
    ]
