# Generated by Django 6.0.1 on 2026-08-10 17:23

from django.db import migrations, models

import soccertime.models


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0035_backfill_image_dimensions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="flag",
            name="image",
            field=models.ImageField(null=True, upload_to=soccertime.models.gen_upload_to),
        ),
        migrations.AlterField(
            model_name="team",
            name="crest",
            field=models.ImageField(null=True, upload_to=soccertime.models.gen_upload_to),
        ),
    ]
