# Generated by Django 6.0.8 on 2026-08-12 11:46

from django.db import migrations, models


def backfill_last_seen(apps, schema_editor):
    """Every existing row starts freshly seen, so the first scrape cannot mass-prune.

    A plain `update()` with no model instances, per the project rule about historical
    models and `post_init`.
    """
    from django.utils import timezone

    apps.get_model("soccertime", "Event").objects.update(last_seen_at=timezone.now())


class Migration(migrations.Migration):
    dependencies = [
        ("soccertime", "0037_event_dates_to_utc"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="last_seen_at",
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name="event",
            name="missing_scrapes",
            field=models.PositiveSmallIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(backfill_last_seen, migrations.RunPython.noop),
    ]
